# Generated by Django 2.2.3 on 2019-12-25 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KayitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=200)),
                ('soyadi', models.CharField(max_length=200)),
                ('cinsiyet', models.CharField(choices=[('1', 'Erkek'), ('2', 'Kız')], max_length=10)),
                ('eposta', models.EmailField(max_length=254)),
                ('tcKimlikNo', models.BigIntegerField()),
                ('kayit_zaman', models.DateTimeField(default=django.utils.timezone.now)),
                ('zaman', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
