# Generated by Django 2.2.3 on 2020-01-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kayit', '0002_auto_20191230_2010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kayitmodel',
            table='kayitlar',
        ),
    ]
